### PR TITLE
Feature/add foundry for testing

### PR DESCRIPTION
**Pull request by opass**
## Integrate Foundry for testing.
1. add an example foundry test
2. add a foundry CI workflow
3. bump curie-contract into 2.1.0 for solving CI issues.

### CODE REVIEW

**Comment by vinta** [comment]
I suppose the failed tests are due to the fix of rounding issues. Though might need to check with @paco0x.
https://github.com/perpetual-protocol/perp-lushan/compare/v2.0.1...v2.1.0

**Comment by opass** [comment]
Hi @vinta, could help review again when you are free?

The primary change is to re-write all tests by **foundry** for limitOrderRewardVault.sol. Also, fix PerpPortal's failing test by consulting @DylanYang0523.

**Comment by paco0x** [comment]
> I suppose the failed tests are due to the fix of rounding issues. Though might need to check with @paco0x. [perpetual-protocol/perp-lushan@v2.0.1...v2.1.0](https://github.com/perpetual-protocol/perp-lushan/compare/v2.0.1...v2.1.0)

yes, there are some rounding behavior differences after the contract upgrade. Thanks for fixing the test cases, looks good to me.

@opass A quick question about git submodules, foundry use submodules for lib dependencies. But it seems this PR brings all files in `lib/forge-std` into our git repo. Did we miss anything?

I thought there should be a `.gitmodules` config in the root directory and `lib/forge-std` should be just a reference to another git repo.

**Comment by opass** [comment]
Hi @paco0x , thanks for pointing out the git-submodules problem.

I follow the [official doc](https://book.getfoundry.sh/config/hardhat#4-steps-to-add-foundry-test) to integrate foundry with hardhat. In demo, it copys the `lib/forge-std` from a new empty foundry project into the existing project.

If we use git-submodule to reference foundry lib, we can keep updated with the latest lib/forge-std. But @vinta suggests using git-submodule is not as convenient as it thought. You need to move into the submodule to pull the latest source code. I am not sure if there is any config to make this process easier. I think we can copy the library first and manually copy the new version in the future if the library is updated.

The current forge std is `v0.1.0`, GitHub repo is [here](https://github.com/foundry-rs/forge-std).

**Comment by opass** [comment]
I am not sure whether using the git submodule would be better or worse to maintain.

**Comment by opass** [comment]
using submodule for foundry lib

**Comment by paco0x** [comment]
> 

We can use

```
git pull
git submodule update --init --recursive
```

to update all the codes in submodules.

**Pull request merged**
